import { defineConfig } from 'vite';
import path from 'node:path';

// Marketing site build: plain HTML/CSS, no framework JS.
// Output goes to dist-site/ and deploys to the S3 bucket ROOT (the editor
// builds separately to dist/ -> /v01/). reference/index.html is generated by
// site/src/generate-reference.ts before this build runs (see build:site).
export default defineConfig({
  root: __dirname,
  base: '/',
  build: {
    outDir: path.resolve(__dirname, '../dist-site'),
    emptyOutDir: true,
    rollupOptions: {
      input: {
        main: path.resolve(__dirname, 'index.html'),
        reference: path.resolve(__dirname, 'reference/index.html'),
      },
    },
  },
});
