import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';

// Every internal href/src on the landing page must point at something that
// exists in the site source (public/ asset or generated page) or at a known
// runtime URL served by other parts of the deployment.
const RUNTIME_URLS = ['/v01/', '/v01/?demo', '/specpad-skill.zip'];

describe('landing page link integrity', () => {
  const siteDir = path.resolve(__dirname, '../..');
  const html = fs.readFileSync(path.join(siteDir, 'index.html'), 'utf8');
  const refs = [...html.matchAll(/(?:href|src)="(\/[^"#]*)/g)].map((m) => m[1]);

  it('references only existing targets', () => {
    const missing = refs.filter((ref) => {
      if (RUNTIME_URLS.includes(ref)) return false;
      if (ref === '/reference/') return false; // generated by build:site — always OK
      if (ref.startsWith('/src/')) return !fs.existsSync(path.join(siteDir, ref.slice(1)));
      return !fs.existsSync(path.join(siteDir, 'public', ref.slice(1)));
    });
    expect(missing).toEqual([]);
  });

  it('has the three core CTAs', () => {
    expect(refs).toContain('/specpad-skill.zip');
    expect(refs.some((r) => r.startsWith('/v01/?demo'))).toBe(true);
    expect(refs).toContain('/reference/');
  });

  it('og-image.png exists in public/', () => {
    expect(fs.existsSync(path.join(siteDir, 'public', 'og-image.png'))).toBe(true);
  });
});
