import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';

// Every internal href/src on the landing page must point at something that
// exists in the site source (public/ asset or generated page) or at a known
// runtime URL served by other parts of the deployment.
const RUNTIME_URLS = ['/v01/', '/v01/?demo', '/specpad-skill.zip'];

describe('landing page link integrity', () => {
  const siteDir = path.resolve(__dirname, '../..');
  const html = fs.readFileSync(path.join(siteDir, 'index.html'), 'utf8');
  const refs = [...html.matchAll(/(?:href|src)="(\/[^"#]*)/g)].map((m) => m[1]);

  it('references only existing targets', () => {
    const missing = refs.filter((ref) => {
      if (RUNTIME_URLS.includes(ref)) return false;
      if (ref === '/reference/') return false; // generated by build:site — always OK
      // A feature page is generated from a template; check the template exists rather than
      // allowlisting the path, so a link to a page nobody wrote still fails.
      const feature = /^\/features\/([a-z-]+)\/$/.exec(ref);
      if (feature) return !fs.existsSync(path.join(siteDir, 'src', 'features', `${feature[1]}.template.html`));
      if (ref.startsWith('/src/')) return !fs.existsSync(path.join(siteDir, ref.slice(1)));
      return !fs.existsSync(path.join(siteDir, 'public', ref.slice(1)));
    });
    expect(missing).toEqual([]);
  });

  it('links every feature page that has a template, and only those', () => {
    const templates = fs.readdirSync(path.join(siteDir, 'src', 'features'))
      .filter((f) => f.endsWith('.template.html'))
      .map((f) => `/features/${f.replace('.template.html', '')}/`);
    expect(templates.length).toBeGreaterThan(0);
    // Every page that exists is reachable from the landing page — a deep dive nobody can
    // find is a page nobody reads.
    for (const t of templates) expect(refs, `${t} is not linked from the landing page`).toContain(t);
  });

  it('has the three core CTAs', () => {
    expect(refs).toContain('/specpad-skill.zip');
    expect(refs.some((r) => r.startsWith('/v01/?demo'))).toBe(true);
    expect(refs).toContain('/reference/');
  });

  it('og-image.png exists in public/', () => {
    expect(fs.existsSync(path.join(siteDir, 'public', 'og-image.png'))).toBe(true);
  });
});

/**
 * Theme binding (JOB-58).
 *
 * The feature pages first shipped with invented custom-property names — `--lp-surface`,
 * `--lp-muted` — so every declaration fell through to its light-theme fallback and rendered
 * white panels under the site's light text. The tokens are the contract between a new
 * component and the theme; using a name the theme does not define fails silently.
 */
describe('stylesheet theme binding', () => {
  const css = fs.readFileSync(path.resolve(__dirname, '../styles.css'), 'utf8');
  // Anything declared anywhere in the stylesheet, plus the ones set inline on an element.
  const defined = new Set([...css.matchAll(/(--[a-z0-9-]+)\s*:/g)].map((m) => m[1]));
  const INLINE = new Set(['--d']); // reveal delay, set per element in the markup

  it('defines the tokens it claims to', () => {
    for (const t of ['--bg', '--surface', '--border', '--text', '--muted', '--accent']) {
      expect(defined.has(t), `${t} is not defined in :root`).toBe(true);
    }
  });

  it('references only tokens the theme defines', () => {
    const used = new Set([...css.matchAll(/var\((--[a-z0-9-]+)/g)].map((m) => m[1]));
    for (const t of used) {
      if (INLINE.has(t)) continue;
      expect(defined.has(t), `styles.css uses ${t}, which the theme does not define`).toBe(true);
    }
  });

  it('uses tokens rather than hard-coded light-theme colours in the feature-page styles', () => {
    // The site is dark; a literal light grey or slate here is the bug this test exists for.
    const docStyles = css.slice(css.indexOf('/* ── Feature pages'));
    for (const literal of ['#f1f5f9', '#e2e8f0', '#64748b', '#fff', '#ffffff']) {
      expect(docStyles, `feature-page styles hard-code ${literal}`).not.toContain(literal);
    }
  });
});
